### ISSUE TITLE
怎么运行

### ISSUE THREAD

**Issue by aiyuekuang** [SymphonyPy/Valified_Code_Classify#1]
能告知下，这个是怎么运行的吗，比如怎么输入一个图片，运行出结果

**Comment by SymphonyPy** [comment]
直接运行Valified_Code_Classify/Classified/Classified.py，需要改一下path（需要识别的图片所在的文件夹）

**Comment by weizixiao** [comment]
方便写一下readme吗

**Comment by SymphonyPy** [comment]
懒得写了。我很久以前写过一个总结，你可以先看看。

**Comment by weizixiao** [comment]
用自己手写的数字，没识别出来。

**Comment by SymphonyPy** [comment]
数据集不一样
